# Site settings
title: "My Results"
baseurl: "/myresults" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
port: 			  4130

# Build settings
#markdown: kramdown
exclude: ["README.md"]

# Extra plugin to create page per item from data sources eg CSV
# https://github.com/avillafiorita/jekyll-datapage_gen

plugins:
  - jekyll-datapage-generator

page_gen:
  - data: 'allmocks'
    template: 'mock'
    dir: 'mock'
    name_expr: 'record["asc"]'
    title: 'title'
